name: OpenWrt_Test
on:
  [push]


env:
  BRANCH_NAME: openwrt-22.03

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Init Building Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get update -y
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y git git-core
          for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done
          sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
          sudo -E apt-get autoremove -y --purge
          sudo -E apt-get clean -y
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile

#      - name: Server Benchmark
#        run: |
#          wget -qO- --no-check-certificate https://raw.githubusercontent.com/Kurokosama/serverbench/main/bench.sh | bash
#

      - name: Clone Source
        run: |
          cd "/home/runner"
          git clone --branch "${BRANCH_NAME}" --single-branch "https://github.com/SaintVamp/openwrt" "openwrt"
          sudo chown -R runner:runner "openwrt"
          release_tag="R2S-$(date +%Y-%m-%d-%H-%M)"
          echo "release_tag=$release_tag" >> $GITHUB_ENV

      - name: Check Source
        id: check_source
        run: |
          cd "/home/runner/openwrt/config"
          ls *.in

      - name: Release
        uses: saintvamp/action-gh-release@v2.1
        with:
          tag_name: ${{ env.release_tag }}
          name: OpenWrt-${{ env.release_tag }}
          body_path: /home/runner/openwrt/config/
          draft: false
          prerelease: false
          files: |
            ${{ steps.check_source.outputs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Source
        run: |
          cd "/home/runner/openwrt/config"
          ls
